name: StaffChatX
version: 1.1.1
main: me.riverm.StaffChatX
commands:
  sc:
    description: Send a Chat message to the online Staff!
    aliases: [s]
  alert:
    description: Send a Server Alert
    aliases: [a, important]